### GENERAL SETTINGS ###

# Site settings
title: Sheldon The Turtle
description: "Check out Sheldon's funny and adorable life now at SheldonTheTurtle.com! Sheldon thanks you in advanced"
baseurl: "" #important: start with /
url: "https://sheldontheturtle.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->

colors:  #in hex code if not noted else
  primary: "#B82601" #"#AEBD38"
  primary_rgb: "43,43,43" #"174,189,56"
  secondary: "#062F4F" #"#2B2B2B"
  link: "#0E8E9E"
  link_hover: "#10A5B8"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Here is the quote for the dailyshell
dailyshell:
  - lines:
    - Sheldon had LOTS of fun today!


email: cweckmaniii@gmail.com
tel: 618-365-0808

# Edit the daily/weekly/monthly fact here!
meal:
 - lines:
   - "Breakfast: Not Hungry"
   - "Lunch: Random Snacks"
   - "Dinner: Bread and Treats from pet store! "


#Shown in footer on every page and also separately on Home and Contact page.
about: "Check out Sheldon's funny and adorable life now at SheldonTheTurtle.com! Sheldon thanks you in advanced!"
