document.write("<a id=\"img81916\"><\/a><div>");
document.write("<time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/19\/16<\/time><article class=\"panel panel-default\">");
document.write("            <div class=\"panel-body\">");
document.write("<a href=\"games\/play\/angry-turtle.swf\">");
document.write("                <img class=\"full img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/thumbnails\/angry_turtle.jpg\">");
document.write("<\/a>");
document.write("<br>");
document.write("<a href=\"games\/play\/frogger.swf\">");
document.write("                <img class=\"full img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/thumbnails\/frogger.jpg\">");
document.write("<\/a>");
document.write("            <\/div>");
document.write("<div class=\"pacif panel-footer\"> <h3>New Games Added!!!<\/h3><\/div>");
document.write("        <\/article>");
document.write("<\/div>");
