document.write("<a id=\"img81216\"><\/a><div>");
document.write("<time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/12\/16<\/time><article class=\"panel panel-default\">");
document.write("            <div class=\"panel-body\">");
document.write("<a href=\"images\/posts\/img81216.jpg\" target=\"_blank\">");
document.write("                <img class=\"gif img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/posts\/img81216.jpg\">");
document.write("<\/a>");
document.write("            <\/div>");
document.write("<div class=\"pacif panel-footer\"> <h3>Going on a trip!<\/h3><\/div>");
document.write("        <\/article>");
document.write("<\/div>");
