document.write("<a id=\"diet81416\"><\/a><div>");
document.write("        <time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/14\/16<\/time><article class=\"panel panel-success\">");
document.write("            <div class=\"panel-heading\">");
document.write("                <h2 class=\"panel-title\">Today He Ate:<\/h2>");
document.write("            <\/div>");
document.write("            <div class=\"panel-body\">Breakfast: Grapes<\/div>");
document.write("            <ul class=\"list-group\">");
document.write("                <li class=\"list-group-item\">Lunch: Bread<\/li>");
document.write("                <li class=\"list-group-item\">Dinner: Skipped<\/li>");
document.write("            <\/ul>");
document.write("        <\/article>");
document.write("<\/div>");
