document.write("<a id=\"img82016\"><\/a><div>");
document.write("<time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/20\/16<\/time><article class=\"panel panel-default\">");
document.write("            <div class=\"panel-body\">");
document.write("<a href=\"images\/posts\/img82016.jpg\" target=\"_blank\">");
document.write("                <img class=\"full img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/posts\/img82016.jpg\">");
document.write("<\/a>");
document.write("            <\/div>");
document.write("<div class=\"pacif panel-footer\"> <h3>Found a twin! <\/h3><\/div>");
document.write("        <\/article>");
document.write("<\/div>");
