document.write("<a id=\"img81816B\"><\/a><div>");
document.write("<time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/18\/16<\/time><article class=\"panel panel-default\">");
document.write("            <div class=\"panel-body\">");
document.write("<a href=\"images\/posts\/img81816B.jpg\" target=\"_blank\">");
document.write("                <img class=\"img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/posts\/img81816B.jpg\">");
document.write("<\/a>");
document.write("            <\/div>");
document.write("<div class=\"pacif panel-footer\"> <h3>Going to the store ^_^<\/h3><\/div>");
document.write("        <\/article>");
document.write("<\/div>");
