document.write("<a id=\"diet8616\"><\/a><div>");
document.write("        <time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/6\/16<\/time><article class=\"panel panel-success\">");
document.write("            <div class=\"panel-heading\">");
document.write("                <h2 class=\"panel-title\">Today He Ate:<\/h2>");
document.write("            <\/div>");
document.write("            <div class=\"panel-body\">Breakfast: Bread<\/div>");
document.write("            <ul class=\"list-group\">");
document.write("                <li class=\"list-group-item\">Lunch: Grapes <\/li>");
document.write("                <li class=\"list-group-item\">Dinner: Tomatoes<\/li>");
document.write("            <\/ul>");
document.write("        <\/article>");
document.write("<\/div>");
