document.write("<a id=\"img8316\"><\/a><div>");
document.write("        <time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/3\/16<\/time><article class=\"panel panel-default\">");
document.write("            <div class=\"panel-body\">");
document.write("<a href=\"images\/posts\/chair_morning.jpg\" target=\"_blank\">");
document.write("                <img class=\"img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/posts\/chair_morning.jpg\">");
document.write("<\/a>");
document.write("            <\/div>");
document.write("        <\/article>");
document.write("<\/div>");
document.write("");
