document.write("<a id=\"img8516A\"><\/a><div>");
document.write("<time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/5\/16<\/time><article class=\"panel panel-default\">");
document.write("            <div class=\"panel-body\">");
document.write("<a href=\"images\/posts\/bed_time_turle.jpg\" target=\"_blank\">");
document.write("                <img class=\"img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/posts\/bed_time_turle.jpg\">");
document.write("<\/a>");
document.write("            <\/div>");
document.write("<div class=\"pacif panel-footer\"> <h4 Bed Time! h4><\/div>");
document.write("        <\/article>");
document.write("<\/div>");
