document.write("<a id=\"img8416A\"><\/a><div>");
document.write("<time><i class=\"glyphicon glyphicon-meter\"><\/i>8\/4\/16<\/time><article class=\"panel panel-default\">");
document.write("            <div class=\"panel-body\">");
document.write("<a href=\"images\/posts\/spikes.jpg\" target=\"_blank\">");
document.write("                <img class=\"img-responsive img-rounded\" alt=\"Image could not be loaded\" src=\"images\/posts\/spikes.jpg\">");
document.write("<\/a>");
document.write("            <\/div>");
document.write("<div class=\"pacif panel-footer\"> <p>Found this old picture of Sheldon!<\/p><\/div>");
document.write("        <\/article>");
document.write("<\/div>");
